const movies = [
  {
    id: 1,
    title: "Project Power",
    img: require("./poster.jpeg"),
    type: "jfy",
    artist: "Jamie Foxx",
  },
  {
    id: 2,
    title: "Sweet Girl",
    img: require("./poster2.jpeg"),
    type: "jfy",
    artist: "Jason Momoa",
  },
  {
    id: 3,
    title: "Vivo",
    img: require("./poster3.jpeg"),
    type: "jfy",
    artist: "Kirk DeMicco",
  },

  {
    id: 4,
    title: "Brutus Vs César",
    img: require("./poster4.jpeg"),
    type: "watched",
    artist: "Kheiron",
  },
  {
    id: 5,
    title: "Aftermath",
    img: require("./poster5.jpeg"),
    type: "listned",
    artist: "Peter Winther",
  },
  {
    id: 6,
    title: "Man in Love",
    img: require("./poster6.jpeg"),
    type: "listned",
    artist: "Yin Chen-Hao",
  },
  {
    id: 7,
    title: "Sarpatta Parambarai",
    img: require("./poster7.jpeg"),
    type: "listned",
    artist: "Pa. Ranjith",
  },
  {
    id: 8,
    title: "Sanitation Day",
    img: require("./poster8.jpeg"),
    type: "watched",
    artist: "Seyi Babatope",
  },
  {
    id: 9,
    title: "Misha and the Wolves",
    img: require("./poster9.jpeg"),
    type: "watched",
    artist: "Sam Hobkinson",
  },
  {
    id: 10,
    title: "Vivo",
    img: require("./poster3.jpeg"),
    type: "watched",
    artist: "Kirk DeMicco",
  },
  {
    id: 11,
    title: "Misha and the Wolves",
    img: require("./poster9.jpeg"),
    type: "listned",
    artist: "Sam Hobkinson",
  },
  {
    id: 12,
    title: "Man in Love",
    img: require("./poster6.jpeg"),
    type: "jfy",
    artist: "Yin Chen-Hao",
  },
  {
    id: 13,
    title: "Vivo",
    img: require("./poster3.jpeg"),
    type: "coming",
    artist: "Kirk DeMicco",
  },
  {
    id: 14,
    title: "Misha and the Wolves",
    img: require("./poster9.jpeg"),
    type: "coming",
    artist: "Sam Hobkinson",
  },
  {
    id: 15,
    title: "Man in Love",
    img: require("./poster6.jpeg"),
    type: "coming",
    artist: "Yin Chen-Hao",
  },
  {
    id: 16,
    title: "Sarpatta Parambarai",
    img: require("./poster7.jpeg"),
    type: "coming",
    artist: "Pa. Ranjith",
  },
  {
    id: 17,
    title: "Misha and the Wolves",
    img: require("./poster9.jpeg"),
    type: "popularmusic",
    artist: "Sam Hobkinson",
  },
  {
    id: 18,
    title: "Vivo",
    img: require("./poster3.jpeg"),
    type: "popularmusic",
    artist: "Kirk DeMicco",
  },
  {
    id: 19,
    title: "Project Power",
    img: require("./poster.jpeg"),
    type: "popularmusic",
    artist: "Jamie Foxx",
  },
  {
    id: 20,
    title: "Aftermath",
    img: require("./poster5.jpeg"),
    type: "popularmusic",
    artist: "Peter Winther",
  },
  {
    id: 21,
    title: "Sarpatta Parambarai",
    img: require("./poster7.jpeg"),
    type: "popilarvideos",
    artist: "Pa. Ranjith",
  },
  {
    id: 22,
    title: "Sanitation Day",
    img: require("./poster8.jpeg"),
    type: "popilarvideos",
    artist: "Seyi Babatope",
  },
  {
    id: 23,
    title: "Man in Love",
    img: require("./poster6.jpeg"),
    type: "popilarvideos",
    artist: "Yin Chen-Hao",
  },
  {
    id: 24,
    title: "Misha and the Wolves",
    img: require("./poster9.jpeg"),
    type: "popilarvideos",
    artist: "Sam Hobkinson",
  },
];

const generes = [
  {
    id: 1,
    name: "Afropop",
    isFav: true,
    subtitle: "",
    img: require("./afropop.jpeg"),
  },
  {
    id: 2,
    name: "Afrotrap",
    isFav: true,
    subtitle: "",
    img: require("./afrotraap.jpeg"),
  },
  {
    id: 3,
    name: "Afrojazz",
    isFav: true,
    subtitle: "",
    img: require("./afrojazz.jpeg"),
  },
  {
    id: 4,
    name: "Pop",
    isFav: true,
    subtitle: "USA/Europe",
    img: require("./pop.jpeg"),
  },
  {
    id: 5,
    name: "RnB",
    isFav: true,
    subtitle: "USA/Europe",
    img: require("./rnb.jpeg"),
  },
  {
    id: 6,
    name: "Hip Hop",
    isFav: true,
    subtitle: "USA/Europe",
    img: require("./hiphop.jpeg"),
  },
  {
    id: 7,
    name: "Afrohouse",
    isFav: false,
    subtitle: "",
    img: require("./afrohouse.jpeg"),
  },
  {
    id: 8,
    name: "Rock",
    isFav: false,
    subtitle: "",
    img: require("./rock.jpeg"),
  },
  {
    id: 9,
    name: "Metal",
    isFav: false,
    subtitle: "",
    img: require("./metal.jpeg"),
  },
  {
    id: 10,
    name: "Salsa",
    isFav: false,
    subtitle: "",
    img: require("./salsa.jpeg"),
  },
  {
    id: 11,
    name: "Reggae",
    isFav: false,
    subtitle: "",
    img: require("./raggae.jpeg"),
  },
  {
    id: 12,
    name: "Zouk",
    isFav: false,
    subtitle: "",
    img: require("./zouk.jpeg"),
  },
  {
    id: 13,
    name: "Tecno",
    isFav: false,
    subtitle: "",
    img: require("./techno.jpeg"),
  },
  {
    id: 14,
    name: "Accoustic",
    isFav: false,
    subtitle: "",
    img: require("./acoustic.jpeg"),
  },
  {
    id: 15,
    name: "Gospel",
    isFav: false,
    subtitle: "",
    img: require("./gospel.jpeg"),
  },
];
// new top classic

const Songs = [
  {
    id: 1,
    title: "NDA",
    artist: "Billie Eilish",
    img: require("./s1.jpg"),
    isLiked: false,
    category: "top",
    duration: "03:15",
  },
  {
    id: 2,
    title: "Don't You Hold Me Down",
    artist: "Alan Walker, Georgia Ku",
    img: require("./s2.jpg"),
    isLiked: true,
    category: "top",
    duration: "02:12",
  },
  {
    id: 3,
    title: "Take My Breath",
    artist: "The Weeknd",
    img: require("./s3.jpg"),
    isLiked: true,
    category: "top",
    duration: "03:40",
  },
  {
    id: 4,
    title: "Run It",
    artist: "DJ Snake,Rick Ross,Rich Brian",
    img: require("./s4.jpg"),
    isLiked: false,
    category: "top",
    duration: "02:44",
  },
  {
    id: 5,
    title: "STAY",
    artist: "The Kid LAROI, Justin Bieber",
    img: require("./s5.jpg"),
    isLiked: true,
    category: "top",
    duration: "02:20",
  },
  {
    id: 6,
    title: "Intentions",
    artist: "Justin Bieber, Quavo",
    img: require("./s6.jpg"),
    isLiked: false,
    category: "top",
    duration: "03:33",
  },
  {
    id: 7,
    title: "Lean On",
    artist: "Celina Sharma,Emiway Bantai",
    img: require("./s7.jpg"),
    isLiked: false,
    category: "top",
    duration: "02:52",
  },
  {
    id: 8,
    title: "Cry for Me",
    artist: "Camila Cabello",
    img: require("./s8.jpg"),
    isLiked: true,
    category: "top",
    duration: "03:09",
  },
  {
    id: 9,
    title: "Living Proof",
    artist: "Camila Cabello",
    img: require("./s9.jpg"),
    isLiked: true,
    category: "top",
    duration: "03:14",
  },
  {
    id: 10,
    title: "What A Man Gotta Do",
    artist: "Jonas Brothers",
    img: require("./s10.jpg"),
    isLiked: false,
    category: "top",
    duration: "03:00",
  },
  {
    id: 11,
    title: "No Judgement",
    artist: "Niall Horan",
    img: require("./s11.jpg"),
    isLiked: true,
    category: "new",
    duration: "02:56",
  },
  {
    id: 12,
    title: "Trampoline",
    artist: "SHAED, Zayn Malik",
    img: require("./s12.jpg"),
    isLiked: false,
    category: "new",
    duration: "03:04",
  },
  {
    id: 13,
    title: "Lights Up",
    artist: "Harry Styles",
    img: require("./s13.jpg"),
    isLiked: true,
    category: "new",
    duration: "02:54",
  },
  {
    id: 14,
    title: "Love Me Now",
    artist: "Kygo, Zoe Wees",
    img: require("./s14.jpg"),
    isLiked: true,
    category: "new",
    duration: "03:15",
  },
  {
    id: 15,
    title: "I Feel Good",
    artist: "Pitbull, Djws",
    img: require("./s15.jpg"),
    isLiked: true,
    category: "new",
    duration: "02:52",
  },
  {
    id: 16,
    title: "Don't Go Yet",
    artist: "Camila Cabello",
    img: require("./s16.jpg"),
    isLiked: false,
    category: "new",
    duration: "02:44",
  },
  {
    id: 17,
    title: "New Normal",
    artist: "Khalid",
    img: require("./s17.jpg"),
    isLiked: false,
    category: "new",
    duration: "03:18",
  },
  {
    id: 18,
    title: "Love Runs Out",
    artist: "Martin Garrix,G-Eazy,Sasha Sloan",
    img: require("./s18.jpg"),
    isLiked: true,
    category: "new",
    duration: "02:44",
  },
  {
    id: 19,
    title: "Arcadia",
    artist: "Lana Del Rey",
    img: require("./s19.jpg"),
    isLiked: false,
    category: "new",
    duration: "04:23",
  },
  {
    id: 20,
    title: "999",
    artist: "Selena Gomez, Camilo",
    img: require("./s20.jpg"),
    isLiked: true,
    category: "new",
    duration: "03:44",
  },
  {
    id: 21,
    title: "Memories",
    artist: "Maroon 5",
    img: require("./s21.jpg"),
    isLiked: false,
    category: "classic",
    duration: "03:09",
  },
  {
    id: 22,
    title: "Alone, Pt. II",
    artist: "Alan Walker, Ava Max",
    img: require("./s22.jpg"),
    isLiked: true,
    category: "classic",
    duration: "02:59",
  },
  {
    id: 23,
    title: "Yummy",
    artist: "Justin Bieber",
    img: require("./s23.jpg"),
    isLiked: true,
    category: "classic",
    duration: "03:28",
  },
  {
    id: 24,
    title: "Believers",
    artist: "Alan Walker, Conor Maynard",
    img: require("./s24.jpg"),
    isLiked: false,
    category: "classic",
    duration: "02:39",
  },
  {
    id: 25,
    title: "Bad Boy",
    artist: "Marwa Loud",
    img: require("./s25.jpg"),
    isLiked: true,
    category: "classic",
    duration: "03:08",
  },
  {
    id: 26,
    title: "bad guy (with Justin",
    artist: "Billie Eilish, Justin Bieber",
    img: require("./s26.jpg"),
    isLiked: false,
    category: "classic",
    duration: "03:14",
  },
  {
    id: 27,
    title: "Liar",
    artist: "Camila Cabello",
    img: require("./s27.jpg"),
    isLiked: true,
    category: "classic",
    duration: "03:27",
  },
  {
    id: 28,
    title: "Shameless",
    artist: "Camila Cabello",
    img: require("./s28.jpg"),
    isLiked: false,
    category: "classic",
    duration: "03:39",
  },
  {
    id: 29,
    title: "Small Talk",
    artist: "Katy Perry",
    img: require("./s29.jpg"),
    isLiked: true,
    category: "classic",
    duration: "02:42",
  },
  {
    id: 30,
    title: "Easy",
    artist: "Camila Cabello",
    img: require("./s30.jpg"),
    isLiked: true,
    category: "classic",
    duration: "03:16",
  },
];

const images = {
  style_cover: require("./style.png"),
  luxury: require("./luxury.png"),
  diamond: require("./diamond.png"),
  fashion: require("./fashion.png"),
  cover_img1: require("./s28.jpg"),
  cover_img2: require("./s27.jpg"),
  cover_img3: require("./s18.jpg"),
  football: require("./football.png"),
  basketball: require("./basketball-ball.png"),
  other_sports: require("./american-football.png"),
  uefa: require("./uefa.jpeg"),
  fifa: require("./fifa-world.jpeg"),
  euro: require("./euro.png"),
  highlights: require("./highlights.png"),
  player_cover: require("./player-title.png"),
  clublogo1: require("./club_logo_1.jpeg"),
  clublogo2: require("./club_logo_2.jpeg"),
  a_madrid: require("./a_madrid.png"),
  real_madridd: require("./real_madrid.jpeg"),
  barcelona: require("./barcelona.jpeg"),
  spider_man_cover: require("./spiderman_cover.png"),
  spider_man: require("./spiderman.png"),
  literature_cover: require("./literature.png"),
  cast1: require("./cast1.png"),
  cast2: require("./cast2.png"),
  cast3: require("./cast3.png"),
  cast4: require("./cast4.png"),
};

const styles_tags = [
  {
    id: 1,
    title: "Fashion",
    icon: images.fashion,
    img: images.cover_img1,
  },
  {
    id: 2,
    title: "Luxury",
    icon: images.luxury,
    img: images.cover_img2,
  },
  {
    id: 3,
    title: "Jewellery",
    icon: images.diamond,
    img: images.cover_img3,
  },
  {
    id: 4,
    title: "Others",
    icon: images.fashion,
    img: images.cover_img2,
  },
];

const app_tags = [
  {
    id: 1,
    title: "Delicouis",
    icon: images.fashion,
    img: images.cover_img1,
  },
  {
    id: 2,
    title: "Wellness",
    icon: images.luxury,
    img: images.cover_img2,
  },
];

const art_tags = [
  {
    id: 1,
    title: "Visual Art",
    icon: images.cover_img3,
    img: images.cover_img1,
  },
  {
    id: 2,
    title: "Perfoming Art",
    icon: images.luxury,
    img: images.cover_img2,
  },
];
// Sport section

const sports_categories = [
  { id: 1, title: "Soccer", icon: images.football },
  { id: 2, title: "Basketball", icon: images.basketball },
  { id: 3, title: "Other", icon: images.other_sports },
];

const sports_sub_categories = [
  { id: 1, title: "UEFA", icon: images.uefa },
  { id: 2, title: "FIFA", icon: images.fifa },
  { id: 3, title: "EURO", icon: images.euro },
];

export default {
  movies,
  generes,
  Songs,
  images,
  styles_tags,
  app_tags,
  sports_categories,
  sports_sub_categories,
  art_tags,
};
